# Site settings
title: FourPark Registry 
description: ERC-721 Assets

# User settings
username: FourPark Registry
user_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque rhoncus sapien nec imperdiet consectetur. Fusce vitae sodales ligula. Pellentesque rhoncus hendrerit facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque bibendum, odio vel iaculis porttitor, velit sapien dapibus elit, commodo finibus nisl ante nec lacus.  
user_title: ERC-721 Assets
email: info@fpreg.io
github_username: 
twitter_username: 
linkedin_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src', 'node_modules', 'bower_components']
